### PR TITLE
Implement intesis local polling

### PR DESCRIPTION
**Pull request by rklomp**
### This implementation is not complete yet
Just to show you my idea and check if you are willing to merge this

-----
This will split the existing `IntesisHome` into a `IntesisHomeBase` class and `IntesisHome` class for cloud connectivity. A new `IntesisHomeLocal` class extends `IntesisHomeBase` and provides connectivity for local pyintesis home devices via the build in webserver.

See https://github.com/rklomp/home-assistant-core/commit/816974e46943c7ecfaa908b215cf259cb615b004 for the required changes to get this into Home Assistant.

It will need some more work. All the config_* items like config_fan_map and config_mode_map are not available from the local API. These are retrieved in a different way using `get_datapoints`. We have to see if we can make the methods that currently use it (like `set_fan_speed`, `get_fan_speed` and `get_fan_speed_list`) more generic, so they can be reused.

At the moment I can set the mode and temperature from my test HA instance. :)

### CODE REVIEW

**Comment by rklomp** [comment]
> It will need some more work. All the config_* items like config_fan_map and config_mode_map are not available from the local API. These are retrieved in a different way using `get_datapoints`. We have to see if we can make the methods that currently use it (like `set_fan_speed`, `get_fan_speed` and `get_fan_speed_list`) more generic, so they can be reused.

See aa7d191. I created a method `_get_fan_map` that can be overridden in the sub-classes. 
I have overridden `has_vertical_swing` and `has_horizontal_swing` (fe772da)

Now able to set mode, temp, fan speed, and swing

**Comment by rklomp** [comment]
@jnimmo , could you give some feedback on this one? If you agree with this concept I will spend more time on it to improve and complete it.

**Comment by Klaas-** [comment]
As a user I would very much enjoy if I could remove my air conditioning from the internet into a local push scenario :)

**Comment by jnimmo** [comment]
Thanks @rklomp I'm excited to see your contributions - sorry I haven't had time to review yet but yes I'm supportive of the idea and the approach you're taking, and happy to work on getting it incorporated.

**Comment by rklomp** [comment]
Thanks for the feedback! I will continue working on it coming week and will let you know when fully ready for review.

@Klaas- Do you have, or are you able to setup, a HA test environment? If you use my HA and pyintesishome branch you should be able to get a working setup already :)

**Comment by Klaas-** [comment]
@rklomp if you need additional testing I can set up a test env

**Comment by rklomp** [comment]
@jnimmo, @Klaas- 
I think this one is ready for review.
My device does not support all modes, so I have not been able to test all functions myself.

**Comment by jnimmo** [comment]
I'll also look to merge in IntesisBox support using a subclass at some stage in the future for the other local control of devices

**Comment by Klaas-** [comment]
I tested cli-example.py on shell, it seems to recognize my devices, did not test any controlling yet.

`{'xxxx / xxxx': {'name': 'DEVICE_xxx', 'widgets': [], 'model': 'MH-AC-WIFI-1', 'power': None, 'mode': None, 'fan_speed': None, 'vvane': None, 'setpoint': None, 'temperature': None, 'remote_controller_lock': None, 'working_hours': None, 'alarm_status': None, 'error_code': None, 'setpoint_min': None, 'setpoint_max': None, 'outdoor_temp': None, 'mainenance_w_reset': None, 'mainenance_wo_reset': None, 'filter_clean': None, 'filter_due_hours': None, 'unknown_uid_acStatus': 0}}`

Maybe you should note the default credentials in readme, for my device they are admin/admin and operator/operator

I'll try to setup a home-assistant test VM later this week and test the other side of the integration.

**Comment by vogel9** [comment]
@rklomp Your changes work great with my Mitsubishi airco! I made a copy with a local version of pyintesishome and added it as a custom component. Had already started making my own integration because I wanted local access, but your work on top of that of @jnimmo saves me a lot of time :-). Thank you very much for the hard work!

**Comment by rklomp** [comment]
@jnimmo , Thanks for merging this!
As soon as a new version is released to pypi, I can propose a new change for Home Assistant as well.

Keep in mind that the work I did on writing tests is not complete yet and requires a lot more work. I might spend more time on this later this month.

**Comment by prjcarr** [comment]
@rklomp Do you have any updates on this local control being available in HA? If its not natively in HA yet, any suggestions on getting it working with pyIntesisHome 1.8?

**Comment by jnimmo** [comment]
I raised PR https://github.com/home-assistant/core/pull/57883 for this yesterday. Please go ahead and test this branch if you can

**Comment by prjcarr** [comment]
#

> I raised PR [home-assistant/core#57883](https://github.com/home-assistant/core/pull/57883) for this yesterday. Please go ahead and test this branch if you can

Awesome. Thank you. Is there any way to tell which IntesisHome devices work with the local control?

**Pull request merged**
